In [23]:
import pandas as pd
import os

In [24]:
# Load the data from the text file
#file_path = 'subset_1_of_TSX1_SAR_SSC_SL_S_SRA_20231230T074146_20231230T074147_Stack_ifg_dinsar_ML_10_flt_TC_geometry_Mask.tx'
#file_path = r"C:\Users\Mohannad Zahra\iceland\Grindavik_Svartsengi_data\The second episode from 2023-12-19 to 2024-01-13\track_49\coh\subset_2_of_TSX1_SAR_SSC_SL_S_SRA_20231230T074146_20231230T074147_Stack_ifg_dinsar_ML_10_flt_TC_geometry_Mask.txt"

file_path = r"C:\Users\Mohannad Zahra\iceland\Grindavik_Svartsengi_data\The fifth episode from 2024-03-17 to 2024-05-28\track_102\coh_2024_05_13\subset_0_of_TDX1_SAR_SSC_SL_S_SRA_20240410T191454_20240410T191456_Stack_ifg_dinsar_ML_10_flt_TC_geometry_Mask.txt"
# Read the file using space as the delimiter
#df = pd.read_csv(file_path, delim_whitespace=True)
data = pd.read_csv(file_path, sep="\t")

In [25]:
#df
data

,Pixel-X,Pixel-Y,Longitude,Latitude,Intensity_ifg_HH_10Apr2024_13May2024_db,Phase_ifg_HH_10Apr2024_13May2024,coh_HH_10Apr2024_13May2024
0,314.5,1608.5,-22.478404,63.856600,256.23640,-2.594592,0.637410
1,315.5,1608.5,-22.478393,63.856600,256.22190,-2.595358,0.637135
2,312.5,1609.5,-22.478427,63.856589,256.32413,-2.583267,0.648190
3,313.5,1609.5,-22.478415,63.856589,256.30850,-2.583961,0.647834
4,310.5,1610.5,-22.478450,63.856577,256.39627,-2.573664,0.657002
...,...,...,...,...,...,...,...
4077,3797.5,121.5,-22.438546,63.873617,256.44083,-1.334680,0.413864
4078,3794.5,122.5,-22.438580,63.873605,256.45923,-1.352472,0.435531
4079,3795.5,122.5,-22.438569,63.873605,256.45218,-1.346891,0.434083
4080,3792.5,123.5,-22.438603,63.873594,256.47882,-1.365459,0.452041
4081,3793.5,123.5,-22.438592,63.873594,256.47055,-1.359757,0.451124

In [27]:
# Calculate the mean of the 'mean_coherence' column
#mean_coh = data['coh_HH_30Dec2023_10Jan2024'].mean()
mean_coh = data['coh_HH_10Apr2024_13May2024'].mean()

# Define the product name and Date (from the file details)
#product_name = 'Mean_subset_2_coh_HH_30Dec2023_10Jan2024'
product_name = 'Mean_subset_0_coh_HH_10Apr2024_13May2024'
Date = '10Apr2024_13May2024'

#Date = '30Dec2023_10Jan20240

In [28]:
# Create a DataFrame with the result
output = pd.DataFrame({
    'Product_Name': [product_name],
    'Date Range': [Date],
    'Mean_coherence': [mean_coh]
})

In [29]:
# Save the result to a CSV file
output_file_path = r"C:\Users\Mohannad Zahra\iceland\Grindavik_Svartsengi_data\coh\mean_coh_0_output_new.csv"
#output_file_path = r"C:\Users\Mohannad Zahra\iceland\Grindavik_Svartsengi_data\coh\mean_coh_1_output_new.csv"
#output_file_path = r"C:\Users\Mohannad Zahra\iceland\Grindavik_Svartsengi_data\coh\mean_coh_2_output_new.csv"

# Append the DataFrame to the CSV file (if the file exists, it will append, otherwise it will create it)
header = not os.path.exists(output_file_path)  # Write header if file doesn't exist

# Save the DataFrame to the local CSV file
output.to_csv(output_file_path, mode='a', header=header, index=False)

# Save the DataFrame to the local CSV file
#output.to_csv(output_file_path, index=False)

print(f"Mean coherence calculated and saved to {output_file_path}")

Mean coherence calculated and saved to C:\Users\Mohannad Zahra\iceland\Grindavik_Svartsengi_data\coh\mean_coh_0_output_new.csv

In [32]:
data0 = r"C:\Users\Mohannad Zahra\iceland\Grindavik_Svartsengi_data\coh\mean_coh_0_output_new.csv"
#data1
data0 = pd.read_csv(data0)
data0

,Product_Name,Date Range,Mean_coherence
0,Mean_subset_0_coh_HH_20Dec2023_31Dec2023,20Dec2023_31Dec2023,0.151901
1,Mean_subset_0_coh_HH_22Dec2023_02Jan2024,22Dec2023_02Jan2024,0.310659
2,Mean_subset_0_coh_HH_30Dec2023_10Jan2024,30Dec2023_10Jan2024,0.186947
3,Mean_subset_0_coh_HH_02Jan2024_13Jan2024,02Jan2024_13Jan2024,0.392628
4,Mean_subset_0_coh_HH_20Jan2024_31Jan2024,20Jan2024_31Jan2024,0.163429
5,Mean_subset_0_coh_HH_12Feb2024_23Feb2024,12Feb2024_23Feb2024,0.283208
6,Mean_subset_0_coh_HH_15Feb2024_26Feb2024,15Feb2024_26Feb2024,0.291308
7,Mean_subset_0_coh_HH_22Feb2024_04Mar2024,22Feb2024_04Mar2024,0.548227
8,Mean_subset_0_coh_HH_19Mar2024_30Mar2024,19Mar2024_30Mar2024,0.463517
9,Mean_subset_0_coh_HH_06Apr2024_17Apr2024,06Apr2024_17Apr2024,0.616949
10,Mean_subset_0_coh_HH_07Apr2024_29Apr2024,07Apr2024_29Apr2024,0.559533
11,Mean_subset_0_coh_HH_10Apr2024_13May2024,10Apr2024_13May2024,0.552029
12,Mean_subset_0_coh_HH_09May2024_20May2024,09May2024_20May2024,0.573510
13,Mean_subset_0_coh_HH_10May2024_21May2024,10May2024_21May2024,0.489626
14,Mean_subset_0_coh_HH_28Mar2024_22May2024,28Mar2024_22May2024,0.563919
15,Mean_subset_0_coh_HH_13May2024_24May2024,13May2024_24May2024,0.464630
16,Mean_subset_0_coh_HH_04Jun2024_07Jul2024,04Jun2024_07Jul2024,0.510353
17,Mean_subset_0_coh_HH_18Jul2024_09Aug2024,18Jul2024_09Aug2024,0.447561

In [30]:
data1 = r"C:\Users\Mohannad Zahra\iceland\Grindavik_Svartsengi_data\coh\mean_coh_1_output_new.csv"
#data1
data1 = pd.read_csv(data1)
data1

,Product_Name,Date Range,Mean_coherence
0,Mean_subset_1_coh_HH_20Dec2023_31Dec2023,20Dec2023_31Dec2023,0.158971
1,Mean_subset_1_coh_HH_22Dec2023_02Jan2024,22Dec2023_02Jan2024,0.258374
2,Mean_subset_1_coh_HH_30Dec2023_10Jan2024,30Dec2023_10Jan2024,0.366509
3,Mean_subset_1_coh_HH_02Jan2024_13Jan2024,02Jan2024_13Jan2024,0.435823
4,Mean_subset_1_coh_HH_20Jan2024_31Jan2024,20Jan2024_31Jan2024,0.379287
5,Mean_subset_1_coh_HH_12Feb2024_23Feb2024,12Feb2024_23Feb2024,0.364430
6,Mean_subset_1_coh_HH_15Feb2024_26Feb2024,15Feb2024_26Feb2024,0.337193
7,Mean_subset_1_coh_HH_22Feb2024_04Mar2024,22Feb2024_04Mar2024,0.650482
8,Mean_subset_1_coh_HH_19Mar2024_30Mar2024,19Mar2024_30Mar2024,0.334660
9,Mean_subset_1_coh_HH_06Apr2024_17Apr2024,06Apr2024_17Apr2024,0.693174
10,Mean_subset_1_coh_HH_07Apr2024_29Apr2024,07Apr2024_29Apr2024,0.698040
11,Mean_subset_1_coh_HH_10Apr2024_13May2024,10Apr2024_13May2024,0.655742
12,Mean_subset_1_coh_HH_09May2024_20May2024,09May2024_20May2024,0.845106
13,Mean_subset_1_coh_HH_10May2024_21May2024,10May2024_21May2024,0.793048
14,Mean_subset_1_coh_HH_28Mar2024_22May2024,28Mar2024_22May2024,0.429077
15,Mean_subset_1_coh_HH_13May2024_24May2024,13May2024_24May2024,0.492028
16,Mean_subset_1_coh_HH_04Jun2024_07Jul2024,04Jun2024_07Jul2024,0.474336
17,Mean_subset_1_coh_HH_18Jul2024_09Aug2024,18Jul2024_09Aug2024,0.520535

In [33]:
data2 = r"C:\Users\Mohannad Zahra\iceland\Grindavik_Svartsengi_data\coh\mean_coh_2_output_new.csv"
#data1
data2 = pd.read_csv(data2)
data2

,Product_Name,Date Range,Mean_coherence
0,Mean_subset_2_coh_HH_20Dec2023_31Dec2023,20Dec2023_31Dec2023,0.235468
1,Mean_subset_2_coh_HH_22Dec2023_02Jan2024,22Dec2023_02Jan2024,0.304674
2,Mean_subset_2_coh_HH_30Dec2023_10Jan2024,30Dec2023_10Jan2024,0.229547
3,Mean_subset_2_coh_HH_02Jan2024_13Jan2024,02Jan2024_13Jan2024,0.438471
4,Mean_subset_2_coh_HH_12Feb2024_23Feb2024,12Feb2024_23Feb2024,0.289471
5,Mean_subset_2_coh_HH_15Feb2024_26Feb2024,15Feb2024_26Feb2024,0.277071
6,Mean_subset_2_coh_HH_22Feb2024_04Mar2024,22Feb2024_04Mar2024,0.380709
7,Mean_subset_2_coh_HH_06Apr2024_17Apr2024,06Apr2024_17Apr2024,0.397598
8,Mean_subset_2_coh_HH_07Apr2024_29Apr2024,07Apr2024_29Apr2024,0.432472
9,Mean_subset_2_coh_HH_09May2024_20May2024,09May2024_20May2024,0.622871
10,Mean_subset_2_coh_HH_10May2024_21May2024,10May2024_21May2024,0.590988
11,Mean_subset_2_coh_HH_28Mar2024_22May2024,28Mar2024_22May2024,0.380690